### 14. Lambda functions in Python

-----
#### What is Lambda function?

A `Lambda` function is a small, anonymous(nameless) written in single line.

📌 Define 
> A lambda fucntion is a one-line function without a name.


#### Why Lambda Function are used?

* ꪜShort and Clean code
* ꪜUsed for temporary operations
* ꪜCommon with map(), filter(), reduce(), apply(), sort()
* ꪜImport readablity in simple logic

#### Normal Function VS Lambda function

syntax:

`(lambda variable:expression)(arguments)`

### Normal Function

In [2]:
def sqrNum(x):  # parameters
    # return x*x
    return x**2
sqrNum(10)  # Function name calling [Invoking]

100

In [3]:
sqrNum(12)

144

### Lambda function

In [5]:
sqrNum1 = (lambda a:a**2)
sqrNum1(10)

100

In [6]:
sqrNum1(12)

144

In [7]:
sqrNum1(16)

256

In [8]:
(lambda a:a**2)(45)

2025

###  Syntax of Lambda function

`(lambda variable:expression)(arguments)`


📌Rules:
* ꪜCan have multiple arguments
* ꪜOnly one expression
* ꪜAutomatically return the result
* ꪜNo return keyword


### Basic Examples

In [10]:
add = (lambda a,b:a+b)
print(add(10,20))

30

In [11]:
print(add(15,45))

60

#### Normal

In [15]:
def checkEven(x):
    if x%2==0:
        return "Even"
checkEven(30)

'Even'

In [19]:
(lambda a:"Even" if a%2==0 else "Odd")(11)

'Odd'

#### Find the maximum of numbers

In [20]:
(lambda a,b,c: a if a>b and a>c else(b if b>a and b>c else c))(10,11,9)

11

### Lambda with built-in function 

1. filter()
2. map()
3. reduce()
4. apply()
5. sort()

syntax:
`filter(function, sequence)`

In [33]:
num = [1,2,3,4,5,6,7,8,9,10]

# Normal 
def checkEven(x):
    if x%2==0:
        return x

In [34]:
num = [1,2,3,4,5,6,7,8,9,10]
list(filter(checkEven,num))

[2, 4, 6, 8, 10]

#### Lambda

In [35]:
num = [1,2,3,4,5,6,7,8,9,10]
list(filter(lambda a:a%2==0,num))

[2, 4, 6, 8, 10]

In [36]:
num = [1,2,3,4,5,6,7,8,9,10]
list(filter(lambda b:b%2!=0,num))

[1, 3, 5, 7, 9]

### Lambda with map()
Purpose: Apply a function to each element in the list.

This function apply calculation to each elements

In [37]:
num = [1,2,3,4,5,6,7,8,9,10]

# Normal Function 

def sqrNum(x):
    return x**2

In [39]:
list(map(sqrNum,num))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [42]:
# Lambda function 

tuple(map(lambda a:a**2,num))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

### Lambda with reduce 

📌 Required Library

`from functools import reduce`

In [43]:
from functools import reduce

In [44]:
help(reduce)

Help on built-in function reduce in module _functools:

reduce(function, iterable, /, initial=<unrepresentable>)
    Apply a function of two arguments cumulatively to the items of an iterable, from left to right.

    This effectively reduces the iterable to a single value.  If initial is
    present, it is placed before the items of the iterable in the
    calculation, and serves as a default when the iterable is empty.

    For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5])
    calculates ((((1 + 2) + 3) + 4) + 5).

In [49]:
# normal Function 

def sumValue(x,y):
    return x+y  # -,*,/,//,%

In [48]:
num = [1,2,3,4,5,6,7,8,9,10]
reduce(sumValue,num)

1

In [50]:
# Lambda function 

num = [1,2,3,4,5,6,7,8,9,10]

reduce(lambda a,b:a+b, num)

55

### Lambda with sorting

In [69]:
students = [("Ram",89),("Anita",85),("Muskan",87),("Ankesh",10)]

sorted_students = sorted(students, key = lambda x:x[0])
print(sorted_students)

[('Anita', 85), ('Ankesh', 10), ('Muskan', 87), ('Ram', 89)]

In [76]:
students = [("Ram",89,5),("Anita",85,10),("Muskan",87,15),("Ankesh",10,3)]
sorted_students = sorted(students, key = lambda x:x[2])
print(sorted_students)

[('Ankesh', 10, 3), ('Ram', 89, 5), ('Anita', 85, 10), ('Muskan', 87, 15)]

### lambda with apply()

### Lambda with apply (only works on dataframe)

Requrired Library 

`import pandas as pd`

In [79]:
import pandas as pd

In [81]:
num = [1,2,3,4,5,6,7,8,9,10]

series  = pd.DataFrame(num)
series

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [82]:
type(series)

pandas.DataFrame

In [87]:
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

df = pd.DataFrame(data)
df

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [89]:
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [91]:
for row in data:
    # print(row)
    for num in row:
        print(num)

1
2
3
4
5
6
7
8
9
10
11
12

In [92]:
df

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [93]:
df1 = df.apply(lambda a:a**2)
df1

     0    1    2
0    1    4    9
1   16   25   36
2   49   64   81
3  100  121  144

Lambda with apply

Example: Increase salary by 10%

In [94]:
data = {
    "Name":["Ram","Anita","Kiran"],
    "Salary":[40000,50000,45000]
}
df = pd.DataFrame(data)
df

    Name  Salary
0    Ram   40000
1  Anita   50000
2  Kiran   45000

In [96]:
df["10% Increment"] = df["Salary"].apply(lambda x:(x*1/10))
df

    Name  Salary  10% Increment
0    Ram   40000         4000.0
1  Anita   50000         5000.0
2  Kiran   45000         4500.0

In [97]:
df["Total Salary"] = df["Salary"] + df["10% Increment"]
df

    Name  Salary  10% Increment  Total Salary
0    Ram   40000         4000.0       44000.0
1  Anita   50000         5000.0       55000.0
2  Kiran   45000         4500.0       49500.0

In [98]:
df["Total Salary New"] = df["Salary"].apply(lambda x:x+(x*1/10))
df

    Name  Salary  10% Increment  Total Salary  Total Salary New
0    Ram   40000         4000.0       44000.0           44000.0
1  Anita   50000         5000.0       55000.0           55000.0
2  Kiran   45000         4500.0       49500.0           49500.0