### 3. Lists in Python


* A List in Python is mutable(Unhashable), ordered, Indexed Based that can store multiple values(Including Mixed data types).

* Lists are one of the most used data types in Python

### 1. List Data

* []

In [2]:
### Empty list
x = []
print(x)
print(type(x))

[]
<class 'list'>

In [4]:
my_list = [1,2,3,4,5,6]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5, 6]
<class 'list'>

#### 2. Feature of List

----


|Feature|Explanation|
|----|----|
|Ordered|Items maintain insertion ordered.|
|Indexed|Each element has index.|
|Mutable|Can modify after creation|
|Allows duplicate|Same value can repeat.|
|Mixed types allowed|Primitive data(int, float, boolean, complex),str,list, tuple, set, dictionary|

In [5]:
mix = [100, 100.23, True, False, "Hello world",["Hello",20,80],(10,20,50),{10,10,20,20,30},{"a":"apple",1:100}]
print(mix)

[100, 100.23, True, False, 'Hello world', ['Hello', 20, 80], (10, 20, 50), {10, 20, 30}, {'a': 'apple', 1: 100}]

### Positive Indexing

In [7]:
print(mix[0])
print(mix[1])

100
100.23

#### Negative Indexing

In [8]:
print(mix[-1])

{'a': 'apple', 1: 100}

In [9]:
print(mix[-3])

(10, 20, 50)

In [10]:
mix = [100, 100.23, True, False, "Hello world",["Hello",20,80],(10,20,50),{10,10,20,20,30},{"a":"apple",1:100}]
print(mix)

[100, 100.23, True, False, 'Hello world', ['Hello', 20, 80], (10, 20, 50), {10, 20, 30}, {'a': 'apple', 1: 100}]

In [12]:
print(mix[-3][1])

20

In [14]:
print(mix[6][1])

20

### Slicing of List


x[:]

In [15]:
mix = [100, 100.23, True, False, "Hello world",["Hello",20,80],(10,20,50),{10,10,20,20,30},{"a":"apple",1:100}]
print(mix)

[100, 100.23, True, False, 'Hello world', ['Hello', 20, 80], (10, 20, 50), {10, 20, 30}, {'a': 'apple', 1: 100}]

In [17]:
mix[2:4]

[True, False]

#### 5. List Mutability

In [18]:
data = [10,20,30,40]
print(data,type(data))

[10, 20, 30, 40] <class 'list'>

In [21]:
## Update of list element
data[0] = 100
data

[100, 20, 30, 40]

### 6. Adding Elemenents to a List

1. append(): append() take one parameter at a time.
2. extend(): extend() take more than one parameter at a time.
3. insert()

In [22]:
nums = [1,2,3]
print(nums)

[1, 2, 3]

In [23]:
nums.append(10)
nums

[1, 2, 3, 10]

In [24]:
nums.append(10)
nums

[1, 2, 3, 10, 10]

### 2.extend()

In [25]:
nums

[1, 2, 3, 10, 10]

In [26]:
nums.extend([100,200,300])
print(nums)

[1, 2, 3, 10, 10, 100, 200, 300]

In [27]:
nums.append([100,200,300])
nums

[1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

### Insert: It takes two parameters at a time.1st parameter is the position of element and 2 is the value.

In [28]:
nums

[1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

In [29]:
nums.insert(0,"Swadhin")
nums

['Swadhin', 1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

#### 7. Removing elements from list

1. remove()
2. pop(n)
3. pop()
4. clear()
5. del()

In [30]:
nums

['Swadhin', 1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

In [31]:
# remove() --> Removes by value

print(nums)

['Swadhin', 1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

In [32]:
nums.remove(300)
nums

['Swadhin', 1, 2, 3, 10, 10, 100, 200, [100, 200, 300]]

In [33]:
# unsafe method
nums.remove(300)
nums

ValueError: list.remove(x): x not in list

### pop(n) --> n is the positision of element

In [35]:
nums

['Swadhin', 1, 2, 3, 10, 10, 100, 200, [100, 200, 300]]

In [36]:
nums.pop(4)
nums

['Swadhin', 1, 2, 3, 10, 100, 200, [100, 200, 300]]

pop(): It automatically remove element at the position of last.

In [37]:
nums.pop()

[100, 200, 300]

In [38]:
nums

['Swadhin', 1, 2, 3, 10, 100, 200]

### clear()

In [40]:
nums.clear()
nums

[]

In [41]:
nums = ['Swadhin', 1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]
nums

['Swadhin', 1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

In [42]:
## delete()

del(nums[0])

In [43]:
nums

[1, 2, 3, 10, 10, 100, 200, 300, [100, 200, 300]]

In [44]:
del(nums)

In [45]:
nums

NameError: name 'nums' is not defined

### 8. List methods: 

----

|Method|Work|
|----|----|
|append(x)|Add item at end|
|extend(iterable)|Add multiple items|
|insert(i,x)|Insert at specific index|
|remove(x)|Remove first occurrence value|
|pop(x)|Remove item at x index|
|pop()| Remove last index value|
|clear()| Remove all items at a time.|
|del()| Delete item|
|index(x)| Return index value of x element|
|sort()|Arrange item in ascending or descending order|
|reverse()| Revesrse list|
|copy()|Return shallow copy|

### 9. index() and count()

In [50]:
nums = [10,20,30,40,50,50]

print(nums.index(40))
print(nums.index(50))
print(nums.count(10))
print(nums.count(50))

3
4
1
2

### 10. Sorting List()

In [52]:
nums = [50,80,10,40,30]
print("Original List:",nums)


nums.sort()
print("After Sorting List items:",nums)

Original List: [50, 80, 10, 40, 30]
After Sorting List items: [10, 30, 40, 50, 80]

In [54]:
nums = [50,80,10,40,30]
print("Original List:",nums)

nums.reverse()
print("After reverse list items:",nums)

Original List: [50, 80, 10, 40, 30]
After reverse list items: [30, 40, 10, 80, 50]

### Descending List

In [58]:
nums = [50,80,10,40,30]
print("Original List:",nums)

nums.sort()
print("After Ascending order:",nums)

Original List: [50, 80, 10, 40, 30]
After Ascending order: [10, 30, 40, 50, 80]

In [59]:
### Slicing of element

desc = nums[::-1]  # reverse
print("Descending Order:",desc)

Descending Order: [80, 50, 40, 30, 10]

In [64]:
nums = [50,80,10,40,30]
print("Original List:",nums)

Original List: [50, 80, 10, 40, 30]

In [65]:
## resverse()
nums.sort()
print("Ascending Order:",x)

Ascending Order: None

In [66]:
nums.reverse()
nums

[80, 50, 40, 30, 10]

### Deep Copy() : ==

#### Shallow copy() : .copy()

## 1. Deep Copy()

In [70]:
x = [10,20]
print("Original List:",x)


y = x  # Assignment operator
print("Duplicate List:",y)

Original List: [10, 20]
Duplicate List: [10, 20]

In [71]:
x.append("Swadhin")
print(x)

[10, 20, 'Swadhin']

In [72]:
print(y)

[10, 20, 'Swadhin']

In [73]:
id(x)

1434892047616

In [74]:
id(y)

1434892047616

In [75]:
x1 = [10,20]
y1 = [10,20,30]

print(x1)
print(y1)

[10, 20]
[10, 20, 30]

In [76]:
id(x1)

1434891991488

In [77]:
id(y1)

1434891990336

### Shallow Copy Using copy()

In [78]:
x = [10,20]
print("Original List:",x)

Original List: [10, 20]

In [79]:
y = x.copy()
print("Duplicate List:",y)

Duplicate List: [10, 20]

In [80]:
x.append("Ankesh")
print(x)

[10, 20, 'Ankesh']

In [81]:
print(y)

[10, 20]

In [82]:
id(x)

1434891989056

In [83]:
id(y)

1434892197184

### 1-D, 2-D, 3-D

In [84]:
matrix = [10,20,30,40,50]   # series
print(matrix)

[10, 20, 30, 40, 50]

In [85]:
import pandas as pd

In [86]:
df = pd.DataFrame(matrix)
df

    0
0  10
1  20
2  30
3  40
4  50

13. Nested List

In [87]:
matrix = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]
print(matrix)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [88]:
df2 = pd.DataFrame(matrix)
df2

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

### Traversing List

-----

In [89]:
nums = [10,20,30]
print(nums)

[10, 20, 30]

In [91]:
print(nums[0])
print(nums[1])
print(nums[2])

10
20
30

In [92]:
for i in nums:
    print(i)

10
20
30

In [95]:
for x in range(len(nums)):
    print(x,nums[x])

0 10
1 20
2 30

### 12. List Concatenation and Repetition

In [97]:
a = [1,2]
b = [3,4]
print(a+b)  # merging of list

[1, 2, 3, 4]

In [99]:
nums = [5,6]

nums*2

[5, 6, 5, 6]

In [100]:
"Swadhin"*2

'SwadhinSwadhin'

### 18. Built in functions

len(): total length of list items

max(): return maximum value

min(): return minimum value

sum(): return sum of the value

In [104]:
nums = [10,20,30]

print(len(nums))
print(min(nums))
print(max(nums))
print(sum(nums))

3
10
30
60

### 19. List vs Tuple

----
|List|Tuple|
|---|---|
|Mutable|Immutable|
|Uses []| Uses ()|
|Slower|Faster|
|More Consume|Less Consume|
|Can be modify|Can't be modify|