### 8. Loops in Python

----------

1. Entry Controlled Loop
    * For-in
    * While
2. Exit Controlled Loop
    * do-while [C,c++,java,javaScript]

`A for loop is used to iterate over a sequence (such as a list, tuple, string, dictionary,set or range) and exeucte a block of code repeatedly.`

## syntax

for variable in sequence:
    
    # code block

Flow:

 1. Python takes the first item from the sequence.
 2. Assign it to the loop variable.
 3. Execute the code block.
 4. Moves to the next item.
 5. Repeats untill all itmes are processed.

In [1]:
fruits = ["Apple","Banana","Mango"]


for var in fruits:
    print(var) # Apple, Banana, Mango

Apple
Banana
Mango

Explanation

---

|Iteration|Fruits Value|
|-----|------|
|1|Apple|
|2|Banana|
|3|Mango|

# Using Range 

range(start,end, striding)

range(end): by default start -0 , end

In [2]:
range(5) #

range(0, 5)

In [3]:
range(10)

range(0, 10)

In [4]:
range(5,11)  # 5 -start   11-stop

range(5, 11)

In [5]:
range(-11)  # by default range added +1 to get next iteratration [wrong range]

range(0, -11)

In [6]:
for i in range(5):
    print(i)

0
1
2
3
4

In [7]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9

In [8]:
for y in range(-10):  # [wrong]
    print(y)

In [9]:
for i in range(5,11):
    print(i)

5
6
7
8
9
10

In [14]:
for i in range(5,20):
    print(i,end=" ")

5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

# striding

In [17]:
for i in range(0,11,2):  # n-1 = 1
    print(i)

0
2
4
6
8
10

In [18]:
for i in range(0,11,3):  # n-1 = 1
    print(i)

0
3
6
9

In [19]:
# Increasing order smallest<greates<greatest<greate

for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [20]:
for i in range(10,-1,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0

### Looping Through a Tuple

In [21]:
colors = ("Red","Green","Blue")

for i in colors:
    print(i)

Red
Green
Blue

## Looping Through a List

In [22]:
numbers = [10,20,30,40,50]

for i in numbers:
    print(i)

10
20
30
40
50

## Looping Through a Dictionary

In [23]:
student = {
    "name":"John",
    "age":55,
    "city":"Pune"
}

In [24]:
student.keys()

dict_keys(['name', 'age', 'city'])

In [25]:
student.values()

dict_values(['John', 55, 'Pune'])

In [26]:
student.items()

dict_items([('name', 'John'), ('age', 55), ('city', 'Pune')])

In [27]:
for key in student:
    print(key)

name
age
city

In [28]:
for key in student.keys():
    print(key)

name
age
city

In [29]:
for value in student.values():
    print(value)

John
55
Pune

In [30]:
for item in student.items():  # packing
    print(item)

('name', 'John')
('age', 55)
('city', 'Pune')

In [33]:
for i,j in student.items():  # unpacking
    print(i,":",j)

name : John
age : 55
city : Pune

Looping Through a Set

In [36]:
nums = {10,20,50,40,40,50,40}
print(nums)

{40, 10, 20, 50}

Sets are unordered, so output may vary.

In [35]:
for i in nums:
    print(i)

40
10
20
50

In [45]:
fruits = ["Apple","Banana","Mango"]

# range()
len(fruits)


for i in range(len(fruits)):
    print(i,fruits[i])

0 Apple
1 Banana
2 Mango

In [41]:
fruits[2]

'Mango'

In [43]:
range(3) # 0,3

range(0, 3)

In [46]:
fruits = ["Apple","Banana","Mango"]

# range()
len(fruits)


for i in range(len(fruits)):
    print(i,fruits[i])

0 Apple
1 Banana
2 Mango

### using enumerate()

In [48]:
for index,value in enumerate(fruits):
    print(index,value)

0 Apple
1 Banana
2 Mango

# Nested Loop 

Loop inside another loop

In [49]:
x = [10,20,30]  # series

y = [[10,20,30],[40,50,60],[70,80,90]]  # dataframe

In [50]:
import pandas as pd

In [51]:
df = pd.DataFrame(x)
df

    0
0  10
1  20
2  30

In [52]:
df1 = pd.DataFrame(y)
df1

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [54]:
for i in range(3):  # 0,1,2
    for j in range(2):  # 0,1
        print(i,j)

0 0
0 1
1 0
1 1
2 0
2 1

In [53]:
0,0
0,1
1,0
1,1
2,0
2,1

(0, 0)

In [55]:
for i in range(4): # 0,1,2,3
    for j in range(6): # 0,1,2,3,4,5   # 24
        print(i,j)

0 0
0 1
0 2
0 3
0 4
0 5
1 0
1 1
1 2
1 3
1 4
1 5
2 0
2 1
2 2
2 3
2 4
2 5
3 0
3 1
3 2
3 3
3 4
3 5

In [ ]:
0,0
0,1
0,2
0,3
0,4
0,5
1,0
1,1
1,2
1,3
1,4
1,5
2,0
2,1
2,2
2,3
2,4
2,5
3,0
3,1
3,2
3,3
3,4
3,5

In [56]:
for i in range(4): # 0,1,2,3
    for j in range(3): # 0,1,2
        for k in range(3): # 0,1,2
            print(i,j,k)

0 0 0
0 0 1
0 0 2
0 1 0
0 1 1
0 1 2
0 2 0
0 2 1
0 2 2
1 0 0
1 0 1
1 0 2
1 1 0
1 1 1
1 1 2
1 2 0
1 2 1
1 2 2
2 0 0
2 0 1
2 0 2
2 1 0
2 1 1
2 1 2
2 2 0
2 2 1
2 2 2
3 0 0
3 0 1
3 0 2
3 1 0
3 1 1
3 1 2
3 2 0
3 2 1
3 2 2

In [ ]:
0,0,0
0,0,1
0,0,2
0,1,0
0,1,1
0,1,2
0,2,0
0,2,1
0,2,2
1,0,0
1,0,1
1,0,2
1,1,0
1,1,1
1,1,2
1,2,0
1,2,1
1,2,2
2,0,0
2,0,1
2,0,2
2,1,0
2,1,1
2,1,2
2,2,0
2,2,1
2,2,2
3,0,0
3,0,1
3,0,2
3,1,0
3,1,1
3,1,2
3,2,0
3,2,1
3,2,2

Break and Continue in For loop

In [58]:
for i in range(11):
    if i == 5:
        break
    print(i)

0
1
2
3
4

In [59]:
for i in range(11):
    print(i)
    if i == 5:  # 5==5
        break

0
1
2
3
4
5

In [60]:
for i in range(11):
    if i == 5:
        break
        print(i)

In [62]:
for i in range(11):
    if i == 5:
        print(i)
        break
    print(i)

0
1
2
3
4
5

### Continue in For loop

In [64]:
for i in range(10):
    if i == 5:  # only one time
        continue
    print(i) # 0 1 2 3 4 6

0
1
2
3
4
6
7
8
9

In [65]:
for i in range(10):
    print(i) # 0 1 2 3 4 6
    if i == 5:  # only one time
        continue

0
1
2
3
4
5
6
7
8
9

In [66]:
for i in range(10):
    print(i) # 0 1 2 3 4 6
    if i == 5:  # only one time
        print(i)
        continue

0
1
2
3
4
5
5
6
7
8
9

In [ ]:
# while loop

In [67]:
for i in range(10): #
    if i == 5: # 
        continue
    print(i)

0
1
2
3
4
5
6
7
8
9

In [69]:
for i in range(10): #
    print(i)
    if i == 5: # only one time i == 5
        print(i)
        continue

0
1
2
3
4
5
5
6
7
8
9

In [ ]:
# while loop

In [2]:
for i in range(1,11):
    print(i)
else:
    print("These are number from 1 to 10")

1
2
3
4
5
6
7
8
9
10
These are number from 1 to 10

### Difference Betweeen for loop and while loop?

----

|For Loop | While Loop|
|---|---|
|Iterate over sequence|Runs based on conditions|
|known Iteration|Unkonwn Iteration|
|Simpler|More Flexible|

### While Loop

A while loop repeatedly executes a block of code as long as condition is True.

For Loop = Known number of iteration.

While Loop = Unknwon number of iterations,depends on a condition.

# 1. What is a While Loop

A while loop check a condition before each iteration.

syntax:

while condition:

    # block of code.

Flow Diagram

----

Start
|
check Condition
|
True ? --------No -----> Exit Loop
|
Exexute code
|
Back to condition

#### display value from 1-5

In [3]:
start = 1

end = 5



while start<=end: # 1<5, 2<5 , 3<5 , 4<5
    print(start) # 1  2 3 4 5
    start = start+1

1
2
3
4
5

In [1]:
start = 1

end = 5

while start<=end: # 1<5
    print(start) 
    start+=1

1
2
3
4
5

In [2]:
## 1 - 10 using while loop

for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [3]:
i = 1

j = 11


while i<j:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10

In [8]:
### table - 19


# 19x1 = 19
# 19x2 = 38
# 19x3 = 57
# 19x4 = 76

num = 19
for i in range(1,11):
    print(num,"x",i,"=",num*i)

19 x 1 = 19
19 x 2 = 38
19 x 3 = 57
19 x 4 = 76
19 x 5 = 95
19 x 6 = 114
19 x 7 = 133
19 x 8 = 152
19 x 9 = 171
19 x 10 = 190

In [9]:
num = 19
for i in range(1,11):
    print(f"{num}x{i}={num*i}")

19x1=19
19x2=38
19x3=57
19x4=76
19x5=95
19x6=114
19x7=133
19x8=152
19x9=171
19x10=190

In [10]:
num = 19
for i in range(1,11):
    print("%dx%d=%d"%(num,i,num*i))

19x1=19
19x2=38
19x3=57
19x4=76
19x5=95
19x6=114
19x7=133
19x8=152
19x9=171
19x10=190

In [12]:
i = 1
j = 11

while i<j:
    print(f"{19}x{i}={19*i}")
    i+=1

19x1=19
19x2=38
19x3=57
19x4=76
19x5=95
19x6=114
19x7=133
19x8=152
19x9=171
19x10=190

## display even numbers from 1-20

In [15]:
for i in range(0,21):
    if i%2 == 0:
        print(i)
    # print(i)

0
2
4
6
8
10
12
14
16
18
20

In [17]:
i = 0

j = 21

while i<j:
    if i%2==0:
        print(i)
    i+=1

0
2
4
6
8
10
12
14
16
18
20

In [20]:
# reverse value from 20-1

for i in range(20,0,-1):
    print(i,end=" ")

20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1

In [22]:
i = 20
j = 0

while i>j:
    print(i,end=" ")
    i = i - 1

20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1

In [26]:
# sum of number from 1 - 10
# 1+2+3+4+5+6+7+8+9+10= 55
# -----

sumValue = 0
for i in range(1,11):
    sumValue = sumValue + i 
    # print(sumValue)
print(f"Sum of value from 1 to 10:{sumValue}")

Sum of value from 1 to 10:55

In [30]:
i = 1

j = 10

sumValue = 0
while i<=j:
    # print(i)
    sumValue = sumValue +  i  # sum of value
    i+=1  # increment of value.
print(f"Sum of the value from 1 to 10: {sumValue}")

Sum of the value from 1 to 10: 55

In [ ]:
# 1 - 5 Nested While loop